# Generated by Django 2.2.5 on 2019-09-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDrug',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.CharField(max_length=100)),
                ('medName', models.CharField(max_length=100)),
                ('Time', models.CharField(max_length=100)),
                ('Way', models.CharField(default='依情況', max_length=100)),
                ('Quantity', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'disease',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('cardID', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Patient Profile',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=100)),
                ('Days', models.IntegerField()),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('TakeMedDate', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(default='submit', max_length=100)),
                ('PatientID', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE, to='mediApp.Patient')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('medName', models.CharField(max_length=100)),
                ('Time', models.CharField(max_length=100)),
                ('Way', models.CharField(max_length=100)),
                ('Quantity', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('PostID', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='mediApp.Post')),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
    ]
