# Generated by Django 2.2.3 on 2019-10-18 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DrugCode', models.CharField(max_length=30)),
                ('MedName', models.CharField(max_length=50)),
                ('Frequency', models.CharField(max_length=30)),
                ('UseTiming', models.CharField(max_length=30)),
                ('Part', models.CharField(max_length=30)),
                ('SideEGrade', models.CharField(max_length=10)),
                ('SideE', models.CharField(max_length=150)),
                ('Discription', models.CharField(max_length=100)),
                ('ImgSrc', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'drug',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardID', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Patient Profile',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=100)),
                ('Days', models.IntegerField()),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('TakeMedDate', models.DateTimeField(auto_now=True)),
                ('AvaTimes', models.IntegerField()),
                ('Times', models.IntegerField()),
                ('Division', models.CharField(max_length=30)),
                ('HosDate', models.DateTimeField()),
                ('Status', models.CharField(default='submit', max_length=100)),
                ('PatientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mediApp.Patient')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DrugCode', models.CharField(max_length=30)),
                ('medName', models.CharField(max_length=100)),
                ('Frequency', models.CharField(max_length=30)),
                ('UseTiming', models.CharField(max_length=30)),
                ('Part', models.CharField(max_length=30)),
                ('SideE', models.CharField(max_length=150)),
                ('Discription', models.CharField(max_length=100)),
                ('timePD', models.IntegerField()),
                ('intervalD', models.IntegerField()),
                ('Alhour', models.IntegerField()),
                ('Alminute', models.IntegerField()),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediApp.Post')),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.CharField(max_length=100)),
                ('Drugs', models.ManyToManyField(to='mediApp.Drug')),
            ],
            options={
                'db_table': 'disease',
            },
        ),
    ]
