# Generated by Django 2.2.3 on 2019-10-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='PerCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='Quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='TotalCost',
            field=models.FloatField(default=0),
        ),
    ]
