# Generated by Django 2.2.3 on 2019-10-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediApp', '0002_auto_20191018_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='PerCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drug',
            name='Quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drug',
            name='TotalCost',
            field=models.FloatField(default=0),
        ),
    ]
