# Generated by Django 2.2.3 on 2019-10-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediApp', '0004_auto_20191024_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='Discription',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='Part',
            new_name='Way',
        ),
        migrations.AlterField(
            model_name='post',
            name='CreateDate',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='TakeMedDate',
            field=models.CharField(max_length=15),
        ),
    ]
