# Generated by Django 2.2.6 on 2019-11-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediApp', '0006_auto_20191024_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='PharmacyID',
            field=models.CharField(default='submit', max_length=100),
        ),
    ]
