# Generated by Django 2.2.6 on 2019-11-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediApp', '0007_post_pharmacyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PharmacyID',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
